/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#291800",
        "surface-container-low": "rgba(255, 255, 255, 0.05)",
        "on-secondary-fixed-variant": "#624000",
        "on-secondary": "#ffffff",
        "surface": "transparent",
        "outline-variant": "rgba(255, 255, 255, 0.1)",
        "surface-tint": "#4c56af",
        "error": "#ba1a1a",
        "surface-variant": "rgba(255, 255, 255, 0.1)",
        "surface-container-lowest": "rgba(0, 0, 0, 0.2)",
        "primary-fixed-dim": "#bdc2ff",
        "surface-container-high": "rgba(255, 255, 255, 0.15)",
        "on-tertiary-container": "#6b95f3",
        "secondary-container": "#FFD700",
        "on-primary": "#000000",
        "tertiary": "#d9e2ff",
        "on-primary-fixed": "#000767",
        "outline": "rgba(255, 255, 255, 0.5)",
        "tertiary-fixed": "#d9e2ff",
        "on-primary-fixed-variant": "#343d96",
        "on-tertiary-fixed-variant": "#00429c",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "rgba(255, 255, 255, 0.2)",
        "error-container": "#ffdad6",
        "on-primary-container": "#8690ee",
        "surface-dim": "rgba(0, 0, 0, 0.5)",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#001945",
        "tertiary-fixed-dim": "#b0c6ff",
        "secondary": "#FFC107",
        "inverse-primary": "#bdc2ff",
        "background": "transparent",
        "surface-bright": "rgba(255, 255, 255, 0.05)",
        "inverse-on-surface": "#f1f1f1",
        "on-background": "#1a1c1c",
        "on-error-container": "#93000a",
        "primary-container": "#1a237e",
        "primary-fixed": "#e0e0ff",
        "on-surface": "#1a1c1c",
        "on-secondary-container": "#684300",
        "secondary-fixed-dim": "#ffb950",
        "on-surface-variant": "#454652",
        "primary": "#3f51b5",
        "inverse-surface": "#1a1c1c",
        "tertiary-container": "#002c6e",
        "surface-container": "rgba(0, 0, 0, 0.05)",
        "secondary-fixed": "#ffddb3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "12px",
        "gutter": "24px",
        "base": "8px",
        "md": "24px",
        "xl": "64px",
        "xs": "4px",
        "lg": "40px",
        "container-max": "1440px"
      },
      fontFamily: {
        "headline-lg": ["Outfit", "sans-serif"],
        "stats-num": ["Outfit", "sans-serif"],
        "display": ["Outfit", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "stats-num": ["28px", {"lineHeight": "1", "fontWeight": "700"}],
        "display": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "600"}],
        "label-bold": ["14px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
